name: Clojure CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        java_version: [corretto-11,corretto-21]
        test_clojure_alias: [clojure-1.10, clojure-1.11, clojure-1.12]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Tools setup
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
    - name: Tools config
      env:
        JAVA_VERSION: ${{matrix.java_version}}
      run: |
        mise use java@$JAVA_VERSION
        mise install
        echo "JAVA_HOME=$(mise where java)" >> $GITHUB_ENV
        echo "$(mise where java)/bin" >> $GITHUB_PATH
    - name: Run tests
      env:
        TEST_CLOJURE_ALIAS: ${{matrix.test_clojure_alias}}
      run: make test TEST_CLOJURE_ALIAS=$TEST_CLOJURE_ALIAS
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Tools setup
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
    - name: Tools config
      run: |
        mise use java@graalvm-22.3.1+java11
        mise install
        echo "JAVA_HOME=$(mise where java)" >> $GITHUB_ENV
        echo "GRAALVM_HOME=$(mise where java)" >> $GITHUB_ENV
        echo "$(mise where java)/bin" >> $GITHUB_PATH
        gu install native-image
    - name: Run tests
      run: make test
    - name: Run clj-kondo linter
      run: make lint
    - name: Run build jar
      run: make build
    - name: Run build app
      run: |
        make build-native
        build/walkr-test-app
